services:
  db:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app          # <-- cohérent avec le healthcheck
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      # Utilise l'utilisateur configuré; se connecte à la DB 'postgres' (toujours présente)
      test: ["CMD-SHELL","pg_isready -U \"$${POSTGRES_USER:-postgres}\" -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "127.0.0.1:5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      # (optionnel) éviter le "master password" à la première connexion :
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin   # <-- volume nommé (persistant et clean)

volumes:
  pgdata:
  pgadmin:
