services:
  db:
    image: postgres:latest
    container_name: postgresql
    restart: always

    # Chargement des variables d'environnement depuis le fichier .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgresql_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

volumes:
  postgresql_data:
    external: true